insert into Countries (code, name, flag_url, region, phone_prefix, trading_allowed) values
('AD', 'Andorra',                           'https://flagcdn.com/w40/ad.png', 'Europe',    '+376',   false),
('AE', 'United Arab Emirates',              'https://flagcdn.com/w40/ae.png', 'Asia',      '+971',   true),
('AF', 'Afghanistan',                       'https://flagcdn.com/w40/af.png', 'Asia',      '+93',    false),
('AG', 'Antigua and Barbuda',               'https://flagcdn.com/w40/ag.png', 'Americas',  '+1268',  false),
('AL', 'Albania',                           'https://flagcdn.com/w40/al.png', 'Europe',    '+355',   true),
('AM', 'Armenia',                           'https://flagcdn.com/w40/am.png', 'Asia',      '+374',   true),
('AO', 'Angola',                            'https://flagcdn.com/w40/ao.png', 'Africa',    '+244',   false),
('AR', 'Argentina',                         'https://flagcdn.com/w40/ar.png', 'Americas',  '+54',    true),
('AT', 'Austria',                           'https://flagcdn.com/w40/at.png', 'Europe',    '+43',    true),
('AU', 'Australia',                         'https://flagcdn.com/w40/au.png', 'Oceania',   '+61',    true),
('AZ', 'Azerbaijan',                        'https://flagcdn.com/w40/az.png', 'Asia',      '+994',   true),
('BA', 'Bosnia and Herzegovina',            'https://flagcdn.com/w40/ba.png', 'Europe',    '+387',   true),
('BB', 'Barbados',                          'https://flagcdn.com/w40/bb.png', 'Americas',  '+1246',  false),
('BD', 'Bangladesh',                        'https://flagcdn.com/w40/bd.png', 'Asia',      '+880',   false),
('BE', 'Belgium',                           'https://flagcdn.com/w40/be.png', 'Europe',    '+32',    true),
('BF', 'Burkina Faso',                      'https://flagcdn.com/w40/bf.png', 'Africa',    '+226',   false),
('BG', 'Bulgaria',                          'https://flagcdn.com/w40/bg.png', 'Europe',    '+359',   true),
('BH', 'Bahrain',                           'https://flagcdn.com/w40/bh.png', 'Asia',      '+973',   true),
('BI', 'Burundi',                           'https://flagcdn.com/w40/bi.png', 'Africa',    '+257',   false),
('BJ', 'Benin',                             'https://flagcdn.com/w40/bj.png', 'Africa',    '+229',   false),
('BN', 'Brunei',                            'https://flagcdn.com/w40/bn.png', 'Asia',      '+673',   false),
('BO', 'Bolivia',                           'https://flagcdn.com/w40/bo.png', 'Americas',  '+591',   false),
('BR', 'Brazil',                            'https://flagcdn.com/w40/br.png', 'Americas',  '+55',    true),
('BS', 'Bahamas',                           'https://flagcdn.com/w40/bs.png', 'Americas',  '+1242',  false),
('BT', 'Bhutan',                            'https://flagcdn.com/w40/bt.png', 'Asia',      '+975',   false),
('BW', 'Botswana',                          'https://flagcdn.com/w40/bw.png', 'Africa',    '+267',   false),
('BY', 'Belarus',                           'https://flagcdn.com/w40/by.png', 'Europe',    '+375',   false),
('BZ', 'Belize',                            'https://flagcdn.com/w40/bz.png', 'Americas',  '+501',   false),
('CA', 'Canada',                            'https://flagcdn.com/w40/ca.png', 'Americas',  '+1',     true),
('CD', 'DR Congo',                          'https://flagcdn.com/w40/cd.png', 'Africa',    '+243',   false),
('CF', 'Central African Republic',          'https://flagcdn.com/w40/cf.png', 'Africa',    '+236',   false),
('CG', 'Republic of the Congo',             'https://flagcdn.com/w40/cg.png', 'Africa',    '+242',   false),
('CH', 'Switzerland',                       'https://flagcdn.com/w40/ch.png', 'Europe',    '+41',    true),
('CI', 'Ivory Coast',                       'https://flagcdn.com/w40/ci.png', 'Africa',    '+225',   false),
('CL', 'Chile',                             'https://flagcdn.com/w40/cl.png', 'Americas',  '+56',    true),
('CM', 'Cameroon',                          'https://flagcdn.com/w40/cm.png', 'Africa',    '+237',   false),
('CN', 'China',                             'https://flagcdn.com/w40/cn.png', 'Asia',      '+86',    false),
('CO', 'Colombia',                          'https://flagcdn.com/w40/co.png', 'Americas',  '+57',    true),
('CR', 'Costa Rica',                        'https://flagcdn.com/w40/cr.png', 'Americas',  '+506',   false),
('CU', 'Cuba',                              'https://flagcdn.com/w40/cu.png', 'Americas',  '+53',    false),
('CV', 'Cape Verde',                        'https://flagcdn.com/w40/cv.png', 'Africa',    '+238',   false),
('CY', 'Cyprus',                            'https://flagcdn.com/w40/cy.png', 'Europe',    '+357',   true),
('CZ', 'Czech Republic',                    'https://flagcdn.com/w40/cz.png', 'Europe',    '+420',   true),
('DE', 'Germany',                           'https://flagcdn.com/w40/de.png', 'Europe',    '+49',    true),
('DJ', 'Djibouti',                          'https://flagcdn.com/w40/dj.png', 'Africa',    '+253',   false),
('DK', 'Denmark',                           'https://flagcdn.com/w40/dk.png', 'Europe',    '+45',    true),
('DM', 'Dominica',                          'https://flagcdn.com/w40/dm.png', 'Americas',  '+1767',  false),
('DO', 'Dominican Republic',                'https://flagcdn.com/w40/do.png', 'Americas',  '+1809',  false),
('DZ', 'Algeria',                           'https://flagcdn.com/w40/dz.png', 'Africa',    '+213',   false),
('EC', 'Ecuador',                           'https://flagcdn.com/w40/ec.png', 'Americas',  '+593',   false),
('EE', 'Estonia',                           'https://flagcdn.com/w40/ee.png', 'Europe',    '+372',   true),
('EG', 'Egypt',                             'https://flagcdn.com/w40/eg.png', 'Africa',    '+20',    true),
('ER', 'Eritrea',                           'https://flagcdn.com/w40/er.png', 'Africa',    '+291',   false),
('ES', 'Spain',                             'https://flagcdn.com/w40/es.png', 'Europe',    '+34',    true),
('ET', 'Ethiopia',                          'https://flagcdn.com/w40/et.png', 'Africa',    '+251',   false),
('FI', 'Finland',                           'https://flagcdn.com/w40/fi.png', 'Europe',    '+358',   true),
('FJ', 'Fiji',                              'https://flagcdn.com/w40/fj.png', 'Oceania',   '+679',   false),
('FR', 'France',                            'https://flagcdn.com/w40/fr.png', 'Europe',    '+33',    true),
('GA', 'Gabon',                             'https://flagcdn.com/w40/ga.png', 'Africa',    '+241',   false),
('GB', 'United Kingdom',                    'https://flagcdn.com/w40/gb.png', 'Europe',    '+44',    true),
('GD', 'Grenada',                           'https://flagcdn.com/w40/gd.png', 'Americas',  '+1473',  false),
('GE', 'Georgia',                           'https://flagcdn.com/w40/ge.png', 'Asia',      '+995',   true),
('GH', 'Ghana',                             'https://flagcdn.com/w40/gh.png', 'Africa',    '+233',   false),
('GM', 'Gambia',                            'https://flagcdn.com/w40/gm.png', 'Africa',    '+220',   false),
('GN', 'Guinea',                            'https://flagcdn.com/w40/gn.png', 'Africa',    '+224',   false),
('GQ', 'Equatorial Guinea',                 'https://flagcdn.com/w40/gq.png', 'Africa',    '+240',   false),
('GR', 'Greece',                            'https://flagcdn.com/w40/gr.png', 'Europe',    '+30',    true),
('GT', 'Guatemala',                         'https://flagcdn.com/w40/gt.png', 'Americas',  '+502',   false),
('GW', 'Guinea-Bissau',                     'https://flagcdn.com/w40/gw.png', 'Africa',    '+245',   false),
('GY', 'Guyana',                            'https://flagcdn.com/w40/gy.png', 'Americas',  '+592',   false),
('HN', 'Honduras',                          'https://flagcdn.com/w40/hn.png', 'Americas',  '+504',   false),
('HR', 'Croatia',                           'https://flagcdn.com/w40/hr.png', 'Europe',    '+385',   true),
('HT', 'Haiti',                             'https://flagcdn.com/w40/ht.png', 'Americas',  '+509',   false),
('HU', 'Hungary',                           'https://flagcdn.com/w40/hu.png', 'Europe',    '+36',    true),
('ID', 'Indonesia',                         'https://flagcdn.com/w40/id.png', 'Asia',      '+62',    true),
('IE', 'Ireland',                           'https://flagcdn.com/w40/ie.png', 'Europe',    '+353',   true),
('IL', 'Israel',                            'https://flagcdn.com/w40/il.png', 'Asia',      '+972',   true),
('IN', 'India',                             'https://flagcdn.com/w40/in.png', 'Asia',      '+91',    true),
('IQ', 'Iraq',                              'https://flagcdn.com/w40/iq.png', 'Asia',      '+964',   false),
('IR', 'Iran',                              'https://flagcdn.com/w40/ir.png', 'Asia',      '+98',    false),
('IS', 'Iceland',                           'https://flagcdn.com/w40/is.png', 'Europe',    '+354',   true),
('IT', 'Italy',                             'https://flagcdn.com/w40/it.png', 'Europe',    '+39',    true),
('JM', 'Jamaica',                           'https://flagcdn.com/w40/jm.png', 'Americas',  '+1876',  false),
('JO', 'Jordan',                            'https://flagcdn.com/w40/jo.png', 'Asia',      '+962',   true),
('JP', 'Japan',                             'https://flagcdn.com/w40/jp.png', 'Asia',      '+81',    true),
('KE', 'Kenya',                             'https://flagcdn.com/w40/ke.png', 'Africa',    '+254',   true),
('KG', 'Kyrgyzstan',                        'https://flagcdn.com/w40/kg.png', 'Asia',      '+996',   false),
('KH', 'Cambodia',                          'https://flagcdn.com/w40/kh.png', 'Asia',      '+855',   false),
('KI', 'Kiribati',                          'https://flagcdn.com/w40/ki.png', 'Oceania',   '+686',   false),
('KM', 'Comoros',                           'https://flagcdn.com/w40/km.png', 'Africa',    '+269',   false),
('KN', 'Saint Kitts and Nevis',             'https://flagcdn.com/w40/kn.png', 'Americas',  '+1869',  false),
('KP', 'North Korea',                       'https://flagcdn.com/w40/kp.png', 'Asia',      '+850',   false),
('KR', 'South Korea',                       'https://flagcdn.com/w40/kr.png', 'Asia',      '+82',    true),
('KW', 'Kuwait',                            'https://flagcdn.com/w40/kw.png', 'Asia',      '+965',   true),
('KZ', 'Kazakhstan',                        'https://flagcdn.com/w40/kz.png', 'Asia',      '+7',     true),
('LA', 'Laos',                              'https://flagcdn.com/w40/la.png', 'Asia',      '+856',   false),
('LB', 'Lebanon',                           'https://flagcdn.com/w40/lb.png', 'Asia',      '+961',   false),
('LC', 'Saint Lucia',                       'https://flagcdn.com/w40/lc.png', 'Americas',  '+1758',  false),
('LI', 'Liechtenstein',                     'https://flagcdn.com/w40/li.png', 'Europe',    '+423',   true),
('LK', 'Sri Lanka',                         'https://flagcdn.com/w40/lk.png', 'Asia',      '+94',    false),
('LR', 'Liberia',                           'https://flagcdn.com/w40/lr.png', 'Africa',    '+231',   false),
('LS', 'Lesotho',                           'https://flagcdn.com/w40/ls.png', 'Africa',    '+266',   false),
('LT', 'Lithuania',                         'https://flagcdn.com/w40/lt.png', 'Europe',    '+370',   true),
('LU', 'Luxembourg',                        'https://flagcdn.com/w40/lu.png', 'Europe',    '+352',   true),
('LV', 'Latvia',                            'https://flagcdn.com/w40/lv.png', 'Europe',    '+371',   true),
('LY', 'Libya',                             'https://flagcdn.com/w40/ly.png', 'Africa',    '+218',   false),
('MA', 'Morocco',                           'https://flagcdn.com/w40/ma.png', 'Africa',    '+212',   true),
('MC', 'Monaco',                            'https://flagcdn.com/w40/mc.png', 'Europe',    '+377',   true),
('MD', 'Moldova',                           'https://flagcdn.com/w40/md.png', 'Europe',    '+373',   true),
('ME', 'Montenegro',                        'https://flagcdn.com/w40/me.png', 'Europe',    '+382',   true),
('MG', 'Madagascar',                        'https://flagcdn.com/w40/mg.png', 'Africa',    '+261',   false),
('MH', 'Marshall Islands',                  'https://flagcdn.com/w40/mh.png', 'Oceania',   '+692',   false),
('MK', 'North Macedonia',                   'https://flagcdn.com/w40/mk.png', 'Europe',    '+389',   true),
('ML', 'Mali',                              'https://flagcdn.com/w40/ml.png', 'Africa',    '+223',   false),
('MM', 'Myanmar',                           'https://flagcdn.com/w40/mm.png', 'Asia',      '+95',    false),
('MN', 'Mongolia',                          'https://flagcdn.com/w40/mn.png', 'Asia',      '+976',   false),
('MR', 'Mauritania',                        'https://flagcdn.com/w40/mr.png', 'Africa',    '+222',   false),
('MT', 'Malta',                             'https://flagcdn.com/w40/mt.png', 'Europe',    '+356',   true),
('MU', 'Mauritius',                         'https://flagcdn.com/w40/mu.png', 'Africa',    '+230',   true),
('MV', 'Maldives',                          'https://flagcdn.com/w40/mv.png', 'Asia',      '+960',   false),
('MW', 'Malawi',                            'https://flagcdn.com/w40/mw.png', 'Africa',    '+265',   false),
('MX', 'Mexico',                            'https://flagcdn.com/w40/mx.png', 'Americas',  '+52',    true),
('MY', 'Malaysia',                          'https://flagcdn.com/w40/my.png', 'Asia',      '+60',    true),
('MZ', 'Mozambique',                        'https://flagcdn.com/w40/mz.png', 'Africa',    '+258',   false),
('NA', 'Namibia',                           'https://flagcdn.com/w40/na.png', 'Africa',    '+264',   false),
('NE', 'Niger',                             'https://flagcdn.com/w40/ne.png', 'Africa',    '+227',   false),
('NG', 'Nigeria',                           'https://flagcdn.com/w40/ng.png', 'Africa',    '+234',   true),
('NI', 'Nicaragua',                         'https://flagcdn.com/w40/ni.png', 'Americas',  '+505',   false),
('NL', 'Netherlands',                       'https://flagcdn.com/w40/nl.png', 'Europe',    '+31',    true),
('NO', 'Norway',                            'https://flagcdn.com/w40/no.png', 'Europe',    '+47',    true),
('NP', 'Nepal',                             'https://flagcdn.com/w40/np.png', 'Asia',      '+977',   false),
('NR', 'Nauru',                             'https://flagcdn.com/w40/nr.png', 'Oceania',   '+674',   false),
('NZ', 'New Zealand',                       'https://flagcdn.com/w40/nz.png', 'Oceania',   '+64',    true),
('OM', 'Oman',                              'https://flagcdn.com/w40/om.png', 'Asia',      '+968',   true),
('PA', 'Panama',                            'https://flagcdn.com/w40/pa.png', 'Americas',  '+507',   true),
('PE', 'Peru',                              'https://flagcdn.com/w40/pe.png', 'Americas',  '+51',    true),
('PG', 'Papua New Guinea',                  'https://flagcdn.com/w40/pg.png', 'Oceania',   '+675',   false),
('PH', 'Philippines',                       'https://flagcdn.com/w40/ph.png', 'Asia',      '+63',    true),
('PK', 'Pakistan',                          'https://flagcdn.com/w40/pk.png', 'Asia',      '+92',    false),
('PL', 'Poland',                            'https://flagcdn.com/w40/pl.png', 'Europe',    '+48',    true),
('PT', 'Portugal',                          'https://flagcdn.com/w40/pt.png', 'Europe',    '+351',   true),
('PW', 'Palau',                             'https://flagcdn.com/w40/pw.png', 'Oceania',   '+680',   false),
('PY', 'Paraguay',                          'https://flagcdn.com/w40/py.png', 'Americas',  '+595',   false),
('QA', 'Qatar',                             'https://flagcdn.com/w40/qa.png', 'Asia',      '+974',   true),
('RO', 'Romania',                           'https://flagcdn.com/w40/ro.png', 'Europe',    '+40',    true),
('RS', 'Serbia',                            'https://flagcdn.com/w40/rs.png', 'Europe',    '+381',   true),
('RU', 'Russia',                            'https://flagcdn.com/w40/ru.png', 'Europe',    '+7',     false),
('RW', 'Rwanda',                            'https://flagcdn.com/w40/rw.png', 'Africa',    '+250',   false),
('SA', 'Saudi Arabia',                      'https://flagcdn.com/w40/sa.png', 'Asia',      '+966',   true),
('SB', 'Solomon Islands',                   'https://flagcdn.com/w40/sb.png', 'Oceania',   '+677',   false),
('SC', 'Seychelles',                        'https://flagcdn.com/w40/sc.png', 'Africa',    '+248',   true),
('SD', 'Sudan',                             'https://flagcdn.com/w40/sd.png', 'Africa',    '+249',   false),
('SE', 'Sweden',                            'https://flagcdn.com/w40/se.png', 'Europe',    '+46',    true),
('SG', 'Singapore',                         'https://flagcdn.com/w40/sg.png', 'Asia',      '+65',    true),
('SI', 'Slovenia',                          'https://flagcdn.com/w40/si.png', 'Europe',    '+386',   true),
('SK', 'Slovakia',                          'https://flagcdn.com/w40/sk.png', 'Europe',    '+421',   true),
('SL', 'Sierra Leone',                      'https://flagcdn.com/w40/sl.png', 'Africa',    '+232',   false),
('SM', 'San Marino',                        'https://flagcdn.com/w40/sm.png', 'Europe',    '+378',   false),
('SN', 'Senegal',                           'https://flagcdn.com/w40/sn.png', 'Africa',    '+221',   false),
('SO', 'Somalia',                           'https://flagcdn.com/w40/so.png', 'Africa',    '+252',   false),
('SR', 'Suriname',                          'https://flagcdn.com/w40/sr.png', 'Americas',  '+597',   false),
('SS', 'South Sudan',                       'https://flagcdn.com/w40/ss.png', 'Africa',    '+211',   false),
('ST', 'São Tomé and Príncipe',             'https://flagcdn.com/w40/st.png', 'Africa',    '+239',   false),
('SV', 'El Salvador',                       'https://flagcdn.com/w40/sv.png', 'Americas',  '+503',   false),
('SY', 'Syria',                             'https://flagcdn.com/w40/sy.png', 'Asia',      '+963',   false),
('SZ', 'Eswatini',                          'https://flagcdn.com/w40/sz.png', 'Africa',    '+268',   false),
('TD', 'Chad',                              'https://flagcdn.com/w40/td.png', 'Africa',    '+235',   false),
('TG', 'Togo',                              'https://flagcdn.com/w40/tg.png', 'Africa',    '+228',   false),
('TH', 'Thailand',                          'https://flagcdn.com/w40/th.png', 'Asia',      '+66',    true),
('TJ', 'Tajikistan',                        'https://flagcdn.com/w40/tj.png', 'Asia',      '+992',   false),
('TL', 'Timor-Leste',                       'https://flagcdn.com/w40/tl.png', 'Asia',      '+670',   false),
('TM', 'Turkmenistan',                      'https://flagcdn.com/w40/tm.png', 'Asia',      '+993',   false),
('TN', 'Tunisia',                           'https://flagcdn.com/w40/tn.png', 'Africa',    '+216',   true),
('TO', 'Tonga',                             'https://flagcdn.com/w40/to.png', 'Oceania',   '+676',   false),
('TR', 'Turkey',                            'https://flagcdn.com/w40/tr.png', 'Europe',    '+90',    true),
('TT', 'Trinidad and Tobago',               'https://flagcdn.com/w40/tt.png', 'Americas',  '+1868',  false),
('TV', 'Tuvalu',                            'https://flagcdn.com/w40/tv.png', 'Oceania',   '+688',   false),
('TZ', 'Tanzania',                          'https://flagcdn.com/w40/tz.png', 'Africa',    '+255',   false),
('UA', 'Ukraine',                           'https://flagcdn.com/w40/ua.png', 'Europe',    '+380',   true),
('UG', 'Uganda',                            'https://flagcdn.com/w40/ug.png', 'Africa',    '+256',   false),
('US', 'United States',                     'https://flagcdn.com/w40/us.png', 'Americas',  '+1',     true),
('UY', 'Uruguay',                           'https://flagcdn.com/w40/uy.png', 'Americas',  '+598',   true),
('UZ', 'Uzbekistan',                        'https://flagcdn.com/w40/uz.png', 'Asia',      '+998',   false),
('VA', 'Vatican City',                      'https://flagcdn.com/w40/va.png', 'Europe',    '+379',   false),
('VC', 'Saint Vincent and the Grenadines', 'https://flagcdn.com/w40/vc.png', 'Americas',  '+1784',  false),
('VE', 'Venezuela',                         'https://flagcdn.com/w40/ve.png', 'Americas',  '+58',    false),
('VN', 'Vietnam',                           'https://flagcdn.com/w40/vn.png', 'Asia',      '+84',    true),
('VU', 'Vanuatu',                           'https://flagcdn.com/w40/vu.png', 'Oceania',   '+678',   false),
('WS', 'Samoa',                             'https://flagcdn.com/w40/ws.png', 'Oceania',   '+685',   false),
('YE', 'Yemen',                             'https://flagcdn.com/w40/ye.png', 'Asia',      '+967',   false),
('ZA', 'South Africa',                      'https://flagcdn.com/w40/za.png', 'Africa',    '+27',    true),
('ZM', 'Zambia',                            'https://flagcdn.com/w40/zm.png', 'Africa',    '+260',   false),
('ZW', 'Zimbabwe',                          'https://flagcdn.com/w40/zw.png', 'Africa',    '+263',   false);

insert into Currencies (code, name, symbol, is_fiat, is_crypto, decimals, is_active) values
-- fiat major
('USD',  'US Dollar',             '$',      true,  false, 2,  true),
('EUR',  'Euro',                  '€',      true,  false, 2,  true),
('GBP',  'British Pound',         '£',      true,  false, 2,  true),
('JPY',  'Japanese Yen',          '¥',      true,  false, 0,  true),
('CHF',  'Swiss Franc',           'Fr',     true,  false, 2,  true),
('CAD',  'Canadian Dollar',       'C$',     true,  false, 2,  true),
('AUD',  'Australian Dollar',     'A$',     true,  false, 2,  true),
('NZD',  'New Zealand Dollar',    'NZ$',    true,  false, 2,  true),
('SEK',  'Swedish Krona',         'kr',     true,  false, 2,  true),
('NOK',  'Norwegian Krone',       'kr',     true,  false, 2,  true),
('DKK',  'Danish Krone',          'kr',     true,  false, 2,  true),
('SGD',  'Singapore Dollar',      'S$',     true,  false, 2,  true),
('HKD',  'Hong Kong Dollar',      'HK$',    true,  false, 2,  true),
-- fiat emerging markets
('RON',  'Romanian Leu',          'lei',    true,  false, 2,  true),
('PLN',  'Polish Zloty',          'zł',     true,  false, 2,  true),
('CZK',  'Czech Koruna',          'Kč',     true,  false, 2,  true),
('HUF',  'Hungarian Forint',      'Ft',     true,  false, 2,  true),
('BGN',  'Bulgarian Lev',         'лв',     true,  false, 2,  true),
('TRY',  'Turkish Lira',          '₺',      true,  false, 2,  true),
('RUB',  'Russian Ruble',         '₽',      true,  false, 2,  false),
('UAH',  'Ukrainian Hryvnia',     '₴',      true,  false, 2,  true),
('BRL',  'Brazilian Real',        'R$',     true,  false, 2,  true),
('MXN',  'Mexican Peso',          '$',      true,  false, 2,  true),
('ZAR',  'South African Rand',    'R',      true,  false, 2,  true),
('INR',  'Indian Rupee',          '₹',      true,  false, 2,  true),
('CNY',  'Chinese Yuan',          '¥',      true,  false, 2,  false),
('KRW',  'South Korean Won',      '₩',      true,  false, 0,  true),
('AED',  'UAE Dirham',            'د.إ',    true,  false, 2,  true),
('SAR',  'Saudi Riyal',           '﷼',      true,  false, 2,  true),
('QAR',  'Qatari Riyal',          'QR',     true,  false, 2,  true),
('MYR',  'Malaysian Ringgit',     'RM',     true,  false, 2,  true),
('THB',  'Thai Baht',             '฿',      true,  false, 2,  true),
('IDR',  'Indonesian Rupiah',     'Rp',     true,  false, 0,  true),
('PHP',  'Philippine Peso',       '₱',      true,  false, 2,  true),
('VND',  'Vietnamese Dong',       '₫',      true,  false, 0,  true),
('ILS',  'Israeli Shekel',        '₪',      true,  false, 2,  true),
('NGN',  'Nigerian Naira',        '₦',      true,  false, 2,  true),
('KES',  'Kenyan Shilling',       'KSh',    true,  false, 2,  true),
('EGP',  'Egyptian Pound',        'E£',     true,  false, 2,  true),
('MAD',  'Moroccan Dirham',       'MAD',    true,  false, 2,  true),
('ARS',  'Argentine Peso',        '$',      true,  false, 2,  true),
('CLP',  'Chilean Peso',          '$',      true,  false, 0,  true),
('COP',  'Colombian Peso',        '$',      true,  false, 2,  true),
('PEN',  'Peruvian Sol',          'S/',     true,  false, 2,  true),
-- crypto
('BTC',  'Bitcoin',               '₿',      false, true,  8,  true),
('ETH',  'Ethereum',              'Ξ',      false, true,  8,  true),
('USDT', 'Tether',                '₮',      false, true,  6,  true),
('USDC', 'USD Coin',              'USDC',   false, true,  6,  true),
('BNB',  'BNB',                   'BNB',    false, true,  8,  true),
('SOL',  'Solana',                'SOL',    false, true,  9,  true),
('XRP',  'XRP',                   'XRP',    false, true,  6,  true),
('ADA',  'Cardano',               'ADA',    false, true,  6,  true),
('AVAX', 'Avalanche',             'AVAX',   false, true,  8,  true),
('DOGE', 'Dogecoin',              'Ð',      false, true,  8,  true),
('DOT',  'Polkadot',              'DOT',    false, true,  8,  true),
('MATIC','Polygon',               'MATIC',  false, true,  8,  true),
('LINK', 'Chainlink',             'LINK',   false, true,  8,  true),
('LTC',  'Litecoin',              'Ł',      false, true,  8,  true),
('UNI',  'Uniswap',               'UNI',    false, true,  8,  true),
('ATOM', 'Cosmos',                'ATOM',   false, true,  6,  true),
('XLM',  'Stellar',               'XLM',    false, true,  7,  true),
('ALGO', 'Algorand',              'ALGO',   false, true,  6,  true),
('NEAR', 'NEAR Protocol',         'NEAR',   false, true,  8,  true),
('ICP',  'Internet Computer',     'ICP',    false, true,  8,  true);



insert into Assets (symbol, name, asset_type, exchange, country_code, currency_code, sector, industry, is_fractionable, is_tradeable, min_order_size, finnhub_symbol, finnhub_mic) values
-- us mega cap tech
('AAPL',  'Apple Inc.',                        'stock', 'NASDAQ', 'US', 'USD', 'Technology',         'Consumer Electronics',        true,  true, 0.000001, 'AAPL',  'XNAS'),
('MSFT',  'Microsoft Corporation',             'stock', 'NASDAQ', 'US', 'USD', 'Technology',         'Software',                    true,  true, 0.000001, 'MSFT',  'XNAS'),
('NVDA',  'NVIDIA Corporation',                'stock', 'NASDAQ', 'US', 'USD', 'Technology',         'Semiconductors',              true,  true, 0.000001, 'NVDA',  'XNAS'),
('GOOGL', 'Alphabet Inc. Class A',             'stock', 'NASDAQ', 'US', 'USD', 'Technology',         'Internet Services',           true,  true, 0.000001, 'GOOGL', 'XNAS'),
('GOOG',  'Alphabet Inc. Class C',             'stock', 'NASDAQ', 'US', 'USD', 'Technology',         'Internet Services',           true,  true, 0.000001, 'GOOG',  'XNAS'),
('AMZN',  'Amazon.com Inc.',                   'stock', 'NASDAQ', 'US', 'USD', 'Consumer Cyclical',  'E-Commerce',                  true,  true, 0.000001, 'AMZN',  'XNAS'),
('META',  'Meta Platforms Inc.',               'stock', 'NASDAQ', 'US', 'USD', 'Technology',         'Social Media',                true,  true, 0.000001, 'META',  'XNAS'),
('TSLA',  'Tesla Inc.',                        'stock', 'NASDAQ', 'US', 'USD', 'Consumer Cyclical',  'Electric Vehicles',           true,  true, 0.000001, 'TSLA',  'XNAS'),
('AVGO',  'Broadcom Inc.',                     'stock', 'NASDAQ', 'US', 'USD', 'Technology',         'Semiconductors',              true,  true, 0.000001, 'AVGO',  'XNAS'),
('ORCL',  'Oracle Corporation',                'stock', 'NYSE',   'US', 'USD', 'Technology',         'Enterprise Software',         true,  true, 0.000001, 'ORCL',  'XNYS'),
-- us finance
('BRK.B', 'Berkshire Hathaway Inc. Class B',   'stock', 'NYSE',   'US', 'USD', 'Financial',          'Insurance',                   true,  true, 0.000001, 'BRK.B', 'XNYS'),
('JPM',   'JPMorgan Chase & Co.',              'stock', 'NYSE',   'US', 'USD', 'Financial',          'Banking',                     true,  true, 0.000001, 'JPM',   'XNYS'),
('V',     'Visa Inc.',                         'stock', 'NYSE',   'US', 'USD', 'Financial',          'Payment Processing',          true,  true, 0.000001, 'V',     'XNYS'),
('MA',    'Mastercard Incorporated',           'stock', 'NYSE',   'US', 'USD', 'Financial',          'Payment Processing',          true,  true, 0.000001, 'MA',    'XNYS'),
('BAC',   'Bank of America Corporation',       'stock', 'NYSE',   'US', 'USD', 'Financial',          'Banking',                     true,  true, 0.000001, 'BAC',   'XNYS'),
('GS',    'Goldman Sachs Group Inc.',          'stock', 'NYSE',   'US', 'USD', 'Financial',          'Investment Banking',          true,  true, 0.000001, 'GS',    'XNYS'),
('MS',    'Morgan Stanley',                    'stock', 'NYSE',   'US', 'USD', 'Financial',          'Investment Banking',          true,  true, 0.000001, 'MS',    'XNYS'),
('WFC',   'Wells Fargo & Company',             'stock', 'NYSE',   'US', 'USD', 'Financial',          'Banking',                     true,  true, 0.000001, 'WFC',   'XNYS'),
('PYPL',  'PayPal Holdings Inc.',              'stock', 'NASDAQ', 'US', 'USD', 'Financial',          'Payment Processing',          true,  true, 0.000001, 'PYPL',  'XNAS'),
-- us healthcare
('LLY',   'Eli Lilly and Company',             'stock', 'NYSE',   'US', 'USD', 'Healthcare',         'Pharmaceuticals',             true,  true, 0.000001, 'LLY',   'XNYS'),
('UNH',   'UnitedHealth Group Inc.',           'stock', 'NYSE',   'US', 'USD', 'Healthcare',         'Health Insurance',            true,  true, 0.000001, 'UNH',   'XNYS'),
('JNJ',   'Johnson & Johnson',                 'stock', 'NYSE',   'US', 'USD', 'Healthcare',         'Pharmaceuticals',             true,  true, 0.000001, 'JNJ',   'XNYS'),
('PFE',   'Pfizer Inc.',                       'stock', 'NYSE',   'US', 'USD', 'Healthcare',         'Pharmaceuticals',             true,  true, 0.000001, 'PFE',   'XNYS'),
('MRK',   'Merck & Co. Inc.',                  'stock', 'NYSE',   'US', 'USD', 'Healthcare',         'Pharmaceuticals',             true,  true, 0.000001, 'MRK',   'XNYS'),
('ABBV',  'AbbVie Inc.',                       'stock', 'NYSE',   'US', 'USD', 'Healthcare',         'Biotechnology',               true,  true, 0.000001, 'ABBV',  'XNYS'),
-- us consumer & retail
('WMT',   'Walmart Inc.',                      'stock', 'NYSE',   'US', 'USD', 'Consumer Defensive', 'Retail',                      true,  true, 0.000001, 'WMT',   'XNYS'),
('COST',  'Costco Wholesale Corporation',      'stock', 'NASDAQ', 'US', 'USD', 'Consumer Defensive', 'Retail',                      true,  true, 0.000001, 'COST',  'XNAS'),
('MCD',   'McDonald''s Corporation',           'stock', 'NYSE',   'US', 'USD', 'Consumer Cyclical',  'Restaurants',                 true,  true, 0.000001, 'MCD',   'XNYS'),
('NKE',   'Nike Inc.',                         'stock', 'NYSE',   'US', 'USD', 'Consumer Cyclical',  'Footwear',                    true,  true, 0.000001, 'NKE',   'XNYS'),
('SBUX',  'Starbucks Corporation',             'stock', 'NASDAQ', 'US', 'USD', 'Consumer Cyclical',  'Restaurants',                 true,  true, 0.000001, 'SBUX',  'XNAS'),
-- us energy
('XOM',   'Exxon Mobil Corporation',           'stock', 'NYSE',   'US', 'USD', 'Energy',             'Oil & Gas',                   true,  true, 0.000001, 'XOM',   'XNYS'),
('CVX',   'Chevron Corporation',               'stock', 'NYSE',   'US', 'USD', 'Energy',             'Oil & Gas',                   true,  true, 0.000001, 'CVX',   'XNYS'),
-- us industrials & other
('BA',    'Boeing Company',                    'stock', 'NYSE',   'US', 'USD', 'Industrials',        'Aerospace & Defense',         true,  true, 0.000001, 'BA',    'XNYS'),
('CAT',   'Caterpillar Inc.',                  'stock', 'NYSE',   'US', 'USD', 'Industrials',        'Construction Equipment',      true,  true, 0.000001, 'CAT',   'XNYS'),
('GE',    'GE Aerospace',                      'stock', 'NYSE',   'US', 'USD', 'Industrials',        'Aerospace & Defense',         true,  true, 0.000001, 'GE',    'XNYS'),
('AMD',   'Advanced Micro Devices Inc.',       'stock', 'NASDAQ', 'US', 'USD', 'Technology',         'Semiconductors',              true,  true, 0.000001, 'AMD',   'XNAS'),
('INTC',  'Intel Corporation',                 'stock', 'NASDAQ', 'US', 'USD', 'Technology',         'Semiconductors',              true,  true, 0.000001, 'INTC',  'XNAS'),
('CRM',   'Salesforce Inc.',                   'stock', 'NYSE',   'US', 'USD', 'Technology',         'Cloud Software',              true,  true, 0.000001, 'CRM',   'XNYS'),
('NFLX',  'Netflix Inc.',                      'stock', 'NASDAQ', 'US', 'USD', 'Communication',      'Streaming',                   true,  true, 0.000001, 'NFLX',  'XNAS'),
('ADBE',  'Adobe Inc.',                        'stock', 'NASDAQ', 'US', 'USD', 'Technology',         'Software',                    true,  true, 0.000001, 'ADBE',  'XNAS'),
('NOW',   'ServiceNow Inc.',                   'stock', 'NYSE',   'US', 'USD', 'Technology',         'Cloud Software',              true,  true, 0.000001, 'NOW',   'XNYS'),
('UBER',  'Uber Technologies Inc.',            'stock', 'NYSE',   'US', 'USD', 'Technology',         'Ridesharing',                 true,  true, 0.000001, 'UBER',  'XNYS'),
('SPOT',  'Spotify Technology S.A.',           'stock', 'NYSE',   'US', 'USD', 'Communication',      'Streaming',                   true,  true, 0.000001, 'SPOT',  'XNYS'),
('COIN',  'Coinbase Global Inc.',              'stock', 'NASDAQ', 'US', 'USD', 'Financial',          'Crypto Exchange',             true,  true, 0.000001, 'COIN',  'XNAS'),
('PLTR',  'Palantir Technologies Inc.',        'stock', 'NYSE',   'US', 'USD', 'Technology',         'Data Analytics',              true,  true, 0.000001, 'PLTR',  'XNYS'),
('SQ',    'Block Inc.',                        'stock', 'NYSE',   'US', 'USD', 'Financial',          'Payment Processing',          true,  true, 0.000001, 'SQ',    'XNYS'),
-- european stocks (adr)
('ASML',  'ASML Holding N.V.',                'stock', 'NASDAQ', 'NL', 'USD', 'Technology',         'Semiconductor Equipment',     true,  true, 0.000001, 'ASML',  'XNAS'),
('SAP',   'SAP SE',                            'stock', 'NYSE',   'DE', 'USD', 'Technology',         'Enterprise Software',         true,  true, 0.000001, 'SAP',   'XNYS'),
('SHEL',  'Shell PLC',                         'stock', 'NYSE',   'GB', 'USD', 'Energy',             'Oil & Gas',                   true,  true, 0.000001, 'SHEL',  'XNYS'),
('TTE',   'TotalEnergies SE',                  'stock', 'NYSE',   'FR', 'USD', 'Energy',             'Oil & Gas',                   true,  true, 0.000001, 'TTE',   'XNYS'),
('NESN',  'Nestlé S.A.',                       'stock', 'NYSE',   'CH', 'USD', 'Consumer Defensive', 'Food & Beverage',             true,  true, 0.000001, 'NESN',  'XNYS'),
-- asian stocks
('TSM',   'Taiwan Semiconductor Manufacturing','stock', 'NYSE',   null, 'USD', 'Technology',         'Semiconductors',              true,  true, 0.000001, 'TSM',   'XNYS'),
('SONY',  'Sony Group Corporation',            'stock', 'NYSE',   'JP', 'USD', 'Technology',         'Consumer Electronics',        true,  true, 0.000001, 'SONY',  'XNYS'),
('BABA',  'Alibaba Group Holding Ltd.',        'stock', 'NYSE',   'CN', 'USD', 'Consumer Cyclical',  'E-Commerce',                  true,  true, 0.000001, 'BABA',  'XNYS'),

-- ============================================================
-- ASSETS — etfs
-- ============================================================
('SPY',   'SPDR S&P 500 ETF Trust',            'etf',   'NYSE',   'US', 'USD', 'Index',              'Broad Market',                true,  true, 0.000001, 'SPY',   'XNYS'),
('QQQ',   'Invesco QQQ Trust',                 'etf',   'NASDAQ', 'US', 'USD', 'Index',              'Technology',                  true,  true, 0.000001, 'QQQ',   'XNAS'),
('IWM',   'iShares Russell 2000 ETF',          'etf',   'NYSE',   'US', 'USD', 'Index',              'Small Cap',                   true,  true, 0.000001, 'IWM',   'XNYS'),
('VTI',   'Vanguard Total Stock Market ETF',   'etf',   'NYSE',   'US', 'USD', 'Index',              'Broad Market',                true,  true, 0.000001, 'VTI',   'XNYS'),
('VOO',   'Vanguard S&P 500 ETF',              'etf',   'NYSE',   'US', 'USD', 'Index',              'Broad Market',                true,  true, 0.000001, 'VOO',   'XNYS'),
('GLD',   'SPDR Gold Shares',                  'etf',   'NYSE',   'US', 'USD', 'Commodities',        'Gold',                        true,  true, 0.000001, 'GLD',   'XNYS'),
('SLV',   'iShares Silver Trust',              'etf',   'NYSE',   'US', 'USD', 'Commodities',        'Silver',                      true,  true, 0.000001, 'SLV',   'XNYS'),
('ARKK',  'ARK Innovation ETF',                'etf',   'NYSE',   'US', 'USD', 'Technology',         'Innovation',                  true,  true, 0.000001, 'ARKK',  'XNYS'),
('XLF',   'Financial Select Sector SPDR Fund', 'etf',   'NYSE',   'US', 'USD', 'Financial',          'Sector ETF',                  true,  true, 0.000001, 'XLF',   'XNYS'),
('XLE',   'Energy Select Sector SPDR Fund',    'etf',   'NYSE',   'US', 'USD', 'Energy',             'Sector ETF',                  true,  true, 0.000001, 'XLE',   'XNYS'),
('XLK',   'Technology Select Sector SPDR Fund','etf',   'NYSE',   'US', 'USD', 'Technology',         'Sector ETF',                  true,  true, 0.000001, 'XLK',   'XNYS'),
('VEA',   'Vanguard FTSE Developed Markets',   'etf',   'NYSE',   'US', 'USD', 'Index',              'International',               true,  true, 0.000001, 'VEA',   'XNYS'),
('EEM',   'iShares MSCI Emerging Markets ETF', 'etf',   'NYSE',   'US', 'USD', 'Index',              'Emerging Markets',            true,  true, 0.000001, 'EEM',   'XNYS'),
('TLT',   'iShares 20+ Year Treasury Bond',    'etf',   'NASDAQ', 'US', 'USD', 'Fixed Income',       'Long-Term Bonds',             true,  true, 0.000001, 'TLT',   'XNAS'),
('BND',   'Vanguard Total Bond Market ETF',    'etf',   'NASDAQ', 'US', 'USD', 'Fixed Income',       'Broad Bonds',                 true,  true, 0.000001, 'BND',   'XNAS'),

-- ============================================================
-- ASSETS — crypto
-- ============================================================
('BTC/USD',   'Bitcoin',        'crypto', null, null, 'USD', 'Crypto', 'Layer 1',        true, true, 0.00001,  'BINANCE:BTCUSDT',   null),
('ETH/USD',   'Ethereum',       'crypto', null, null, 'USD', 'Crypto', 'Layer 1',        true, true, 0.0001,   'BINANCE:ETHUSDT',   null),
('SOL/USD',   'Solana',         'crypto', null, null, 'USD', 'Crypto', 'Layer 1',        true, true, 0.01,     'BINANCE:SOLUSDT',   null),
('BNB/USD',   'BNB',            'crypto', null, null, 'USD', 'Crypto', 'Exchange Token', true, true, 0.001,    'BINANCE:BNBUSDT',   null),
('XRP/USD',   'XRP',            'crypto', null, null, 'USD', 'Crypto', 'Payment',        true, true, 1,        'BINANCE:XRPUSDT',   null),
('ADA/USD',   'Cardano',        'crypto', null, null, 'USD', 'Crypto', 'Layer 1',        true, true, 1,        'BINANCE:ADAUSDT',   null),
('AVAX/USD',  'Avalanche',      'crypto', null, null, 'USD', 'Crypto', 'Layer 1',        true, true, 0.01,     'BINANCE:AVAXUSDT',  null),
('DOGE/USD',  'Dogecoin',       'crypto', null, null, 'USD', 'Crypto', 'Meme Coin',      true, true, 1,        'BINANCE:DOGEUSDT',  null),
('DOT/USD',   'Polkadot',       'crypto', null, null, 'USD', 'Crypto', 'Layer 0',        true, true, 0.1,      'BINANCE:DOTUSDT',   null),
('LINK/USD',  'Chainlink',      'crypto', null, null, 'USD', 'Crypto', 'Oracle',         true, true, 0.1,      'BINANCE:LINKUSDT',  null),
('LTC/USD',   'Litecoin',       'crypto', null, null, 'USD', 'Crypto', 'Payment',        true, true, 0.01,     'BINANCE:LTCUSDT',   null),
('UNI/USD',   'Uniswap',        'crypto', null, null, 'USD', 'Crypto', 'DeFi',           true, true, 0.1,      'BINANCE:UNIUSDT',   null),
('ATOM/USD',  'Cosmos',         'crypto', null, null, 'USD', 'Crypto', 'Layer 0',        true, true, 0.1,      'BINANCE:ATOMUSDT',  null),
('NEAR/USD',  'NEAR Protocol',  'crypto', null, null, 'USD', 'Crypto', 'Layer 1',        true, true, 0.1,      'BINANCE:NEARUSDT',  null),
('MATIC/USD', 'Polygon',        'crypto', null, null, 'USD', 'Crypto', 'Layer 2',        true, true, 1,        'BINANCE:MATICUSDT', null);

-- ============================================================
-- FX RATES (static snapshot — updated from backend)
-- ============================================================

insert into FX_Rates (base_currency, quote_currency, rate, bid, ask, source) values
('USD', 'EUR', 0.92150000, 0.92130000, 0.92170000, 'finnhub'),
('USD', 'GBP', 0.79200000, 0.79180000, 0.79220000, 'finnhub'),
('USD', 'JPY', 149.85000000, 149.83000000, 149.87000000, 'finnhub'),
('USD', 'CHF', 0.89500000,  0.89480000,  0.89520000,  'finnhub'),
('USD', 'CAD', 1.36200000,  1.36180000,  1.36220000,  'finnhub'),
('USD', 'AUD', 1.53800000,  1.53780000,  1.53820000,  'finnhub'),
('USD', 'NZD', 1.63500000,  1.63480000,  1.63520000,  'finnhub'),
('USD', 'SEK', 10.42000000, 10.41800000, 10.42200000, 'finnhub'),
('USD', 'NOK', 10.58000000, 10.57800000, 10.58200000, 'finnhub'),
('USD', 'DKK', 6.88000000,  6.87800000,  6.88200000,  'finnhub'),
('USD', 'SGD', 1.34200000,  1.34180000,  1.34220000,  'finnhub'),
('USD', 'HKD', 7.82500000,  7.82300000,  7.82700000,  'finnhub'),
('USD', 'RON', 4.58000000,  4.57800000,  4.58200000,  'finnhub'),
('USD', 'PLN', 3.97000000,  3.96800000,  3.97200000,  'finnhub'),
('USD', 'CZK', 23.15000000, 23.13000000, 23.17000000, 'finnhub'),
('USD', 'HUF', 357.50000000,357.30000000,357.70000000,'finnhub'),
('USD', 'TRY', 32.15000000, 32.13000000, 32.17000000, 'finnhub'),
('USD', 'BRL', 4.97000000,  4.96800000,  4.97200000,  'finnhub'),
('USD', 'MXN', 17.15000000, 17.13000000, 17.17000000, 'finnhub'),
('USD', 'ZAR', 18.72000000, 18.70000000, 18.74000000, 'finnhub'),
('USD', 'INR', 83.20000000, 83.18000000, 83.22000000, 'finnhub'),
('USD', 'KRW', 1325.00000000,1324.50000000,1325.50000000,'finnhub'),
('USD', 'AED', 3.67300000,  3.67100000,  3.67500000,  'finnhub'),
('USD', 'SAR', 3.75000000,  3.74800000,  3.75200000,  'finnhub'),
('USD', 'QAR', 3.64000000,  3.63800000,  3.64200000,  'finnhub'),
('USD', 'MYR', 4.71000000,  4.70800000,  4.71200000,  'finnhub'),
('USD', 'THB', 35.20000000, 35.18000000, 35.22000000, 'finnhub'),
('USD', 'IDR', 15680.00000000,15675.00000000,15685.00000000,'finnhub'),
('USD', 'PHP', 56.50000000, 56.48000000, 56.52000000, 'finnhub'),
('USD', 'ILS', 3.72000000,  3.71800000,  3.72200000,  'finnhub'),
('USD', 'NGN', 1540.00000000,1538.00000000,1542.00000000,'finnhub'),
('USD', 'EGP', 48.50000000, 48.48000000, 48.52000000, 'finnhub'),
('USD', 'MAD', 10.05000000, 10.04000000, 10.06000000, 'finnhub'),
('USD', 'ARS', 987.00000000,986.00000000,988.00000000,'finnhub'),
('USD', 'BRL', 4.97000000,  4.96800000,  4.97200000,  'finnhub'),
('EUR', 'USD', 1.08510000,  1.08490000,  1.08530000,  'finnhub'),
('EUR', 'GBP', 0.85900000,  0.85880000,  0.85920000,  'finnhub'),
('EUR', 'RON', 4.97500000,  4.97300000,  4.97700000,  'finnhub'),
('EUR', 'PLN', 4.30000000,  4.29800000,  4.30200000,  'finnhub'),
('EUR', 'CZK', 25.12000000, 25.10000000, 25.14000000, 'finnhub'),
('EUR', 'HUF', 387.50000000,387.30000000,387.70000000,'finnhub'),
('EUR', 'CHF', 0.97100000,  0.97080000,  0.97120000,  'finnhub'),
('EUR', 'JPY', 162.50000000,162.48000000,162.52000000,'finnhub'),
('GBP', 'USD', 1.26300000,  1.26280000,  1.26320000,  'finnhub'),
('GBP', 'EUR', 1.16400000,  1.16380000,  1.16420000,  'finnhub'),
('GBP', 'JPY', 189.20000000,189.18000000,189.22000000,'finnhub');